apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-eks-automated
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 0
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    spec:
      containers:

        -
          name: luther007/jenkins-eks-automated
          image: latest
          ports:
            -
              name: 'expose port 4200'
              containerPort: 4200
              hostPort: 4200
              protocol: TCP
      volumes: []