apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-eks-automated
  labels:
    app: mike
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 0
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mike
    spec:
      containers:
        - name: mike1
          image: luther007/jenkins-eks-automated:latest
          ports:
            - containerPort: 4200
              hostPort: 4200
              protocol: TCP
      volumes: []