apiVersion: v1
kind: Service
metadata:
  name: mike-load-balancer
  namespace: feature
spec:
  type: LoadBalancer
  selector:
    app: mike
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      name: http