branch-defaults:
  default:
    environment: development
    group_suffix: null
global:
  application_name: eb-govcloudsample
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-gov-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
