# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: luther007/jenkins-eks-automated-feature
  tag: latest
  pullPolicy: Always

# define environment variables here as a map of key: value
env:
hpa:
  minReplicas: 1
  maxReplicas: 3
# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: puppet-pipeline-test
  type: LoadBalancer
  externalPort: 4200
  internalPort: 4200
  # annotations:
  #   fabric8.io/expose: "true"
  #   fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  requests:
    cpu: 200m
    memory: 128Mi
  # limits:
  #   cpu: 400m
  #   memory: 256Mi

# probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
